language: python
python:
    - "2.7"

# Cache PlatformIO packages
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio run
    
